DRAGON_PATH = "asset/dragon.png"
KNIGHT_PATH = "asset/knight_cat.png"
ELIOT_PATH = "asset/Eliot.png"


WALL_0 = "asset/0000.png"
WALL_1 = "asset/mur_haut.png"
WALL_10 = "asset/mdroit.png"
WALL_11 = "asset/coinhdoit.png"
WALL_100 = "asset/mur_bas.png"
WALL_101 = "asset/couloir_dr.png"
WALL_110 = "asset/coinbdoit.png"
WALL_111 = "asset/pmgauche.png"
WALL_1000 = "asset/mgauche.png"
WALL_1100 = "asset/coinbgauch.png"
WALL_1010 = "asset/couloir_hb.png"
WALL_1001 = "asset/coinhgauch.png"
WALL_1011 = "asset/pmbas.png"
WALL_1110 = "asset/pmhaut.png"
WALL_1111 = "asset/1111.png"
WALL_1101 = "asset/pmdroit.png"

PAC_GUM = "asset/pac_gum.jpg"
